Database didn't set up. Adding wait time before creating db

diff --git a/.github/workflows/test-actions.yaml b/.github/workflows/test-actions.yaml
--- a/.github/workflows/test-actions.yaml
+++ b/.github/workflows/test-actions.yaml
@@ -19,7 +19,16 @@ jobs:
       - name: Start PostgreSQL Server
         run: sudo systemctl start postgresql
 
-      - name: Create testDB and User
+      - name: Wait for PostgreSQL to start
+        run: |
+          for i in {1..5}; do
+            sudo systemctl is-active --quiet postgresql && break
+            sleep 10
+          done
+          sudo systemctl is-active --quiet postgresql || (echo "PostgreSQL service failed to start within the timeout period." && exit 1)
+          echo "PostgreSQL service started successfully."
+
+      - name: Create Database and User
         run: |
           sudo -u postgres psql -c "CREATE USER ${{ secrets.DB_USER }} WITH PASSWORD '${{ secrets.DB_PASSWORD }}';"
           sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_NAME }};"
